language: python

python:
  - "3.7"
  - "3.8"

install:
  # Ensure virtualenv is up to date to avoid DeprecationWarning in bundled site.py.
  - pip install --upgrade virtualenv
  - pip install -r requirements.txt
  - pip install .

script: python -m unittest discover -v -s tests -p test_*.py

notifications:
  email: false